baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "Jacob Kohav's portfolio"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"
    
Paginate: 3
enableRobotsTXT: true

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  # main: # Enable when a menu item is added
    # - identifier: blog
    #   name: Blog
    #   title: Blog posts
    #   url: /blogs
    #   weight: 1
    # - identifier: gallery
    #   name: Gallery
    #   title: Blog posts
    #   url: /gallery
    #   weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Hugo Profile"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    disableThemeToggle: true
    defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  color:
    # textColor: 
    # secondaryTextColor:
    # backgroundColor:  # Original
    # backgroundColor:  #ebf5fb 
    # backgroundColor:  #fdfefe 
    # secondaryBackgroundColor:
    # primaryColor:
    # secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    brandName: "Jacob Kohav" # Brand name for the brand | default is the title variable
    disableSearch: false
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Jacob."
    subtitle: "I build things for the web"
    content: "A passionate web app developer. I tend to make use of modern web technologies to build websites that looks great, feels fantastic, and functions correctly."
    # image: /images/hero.svg
    # image: /Simultion_of_Flocks.jpg # Doesn't work!
    button:
      enable: false
      name: "Resume"
      url: "#"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/JacobKohav
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/jacob-kohav/
        - icon: fa fa-envelope
          url: mailto:jacob.kohav@colorado.edu?subject=Connect%20with%20Jacob
      customIcons:
        - icon: /fav.png
          url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.png"
    content: |-
      I am a software developer with a passion for web development. I have a background in computer science and mathematics, and I have a strong interest in the intersection of technology and art. I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. 

      I am currently working on a project that will be used to help people find the best way to get around the city.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "HTML"
        - "CSS"
        - "JavaScript"
        - "React"
        - "Node"
        - "Express"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "AI/ML Research Engineer"
        company: "Lockheed Martin"
        companyUrl: "https://www.lockheedmartin.com/en-us/index.html"
        date: "Feb 2022 - present"
        info:
          enable: false
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

      - job: "Software Engineer"
        company: "Lockheed Martin"
        companyUrl: "https://www.lockheedmartin.com/en-us/index.html"
        date: "Mar 2021 - Feb 2022"
        featuredLink:
          enable: false
          url: "https://example.com"
        info:
          enable: false
          content: I worked as a software developer for more than one year in Amazon.
        content: |
          I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

          - Lead backend developer for a product.
          - Created a frontend design for a product.

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Masters of Science in Data Science"
        school:
          name: "University of Colorado, Boulder"
          url: "https://www.colorado.edu/"
        date: "2021 - present"
        GPA: "-"
        content: |-
          Extracurricular Activities
            - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
      
      - title: "Masters of Engineering in Engineering Management"
        school:
          name: "University of Colorado, Boulder"
          url: "https://www.colorado.edu/"
        date: "2022 - present"
        GPA: "-"
        content: |-
          Extracurricular Activities
            - Lorem ipsum dolor sit amet consectetur adipisicing elit. 

      - title: "Bachelors in Computer Science"
        school:
          name: "University of Colorado, Boulder"
          url: "https://www.colorado.edu/"
        date: "- 2020"
        GPA: "-"
        content: |-
          Extracurricular Activities
            - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
        featuredLink:
          enable: false
          name: "My academic record"
          url: "https://example.com"

  # Achievements
  achievements:
    enable: true
    # title: "Custom Name"
    items:
      - title: Leading SAFe
        content: I solved all problems with optimal.
        icon: fa fa-envelope
        url: https://example.com
        links:
          - icon: fab fa-github
            url: https://github.com/JacobKohav/NYPD_Shooting_Incident
        
          # url: "https://example.com"
      # - title: Facebook Hackathon Winner
      #   content: Developed a product using Artificial Intelligence.
      # - title: Hugo Profile
      #   content: Developed a theme and getting 1K+ downloads per month.
      #   url: "https://github.com/gurusabarish/hugo-profile"
      # - title: Microsoft Imagine Runner
      #   content: We are developed a product which can help others.
      # - title: Google Summer of Code
      #   content: Contributed to a open source project.
      #   url: https://example.com

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
    # Analysis of NYPD Shooting Incidents with the following Data Science techniques 1. Importing 2. Cleaning 3. Transformation 4. Analysis 5. Visualization 6. Bias Identification along with a summary and conclusion.

      - title: NYPD Shooting Incidents Analysis
        content: Analysis of NYPD Shooting Incidents with the following Data Science techniques 1. Importing 2. Cleaning 3. Transformation 4. Analysis 5. Visualization 6. Bias Identification along with a summary and conclusion.
        image: https://i.ytimg.com/vi/4ZUXYOTiZsg/maxresdefault.jpg
        # featured:
        #   name: Demo
        #   link: https://hugo-profile.netlify.app
        badges:
          - "R"
          - "Modelling"
          - "Data Cleaning"
          - "Statistical Analysis"
        links:
          - icon: fab fa-github
            url: https://github.com/JacobKohav/NYPD_Shooting_Incident
          # - icon: fab fa-twitter
          #   url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Simulation of Random Walks
        content: 
         Animal movement predictions through a random walk simulation. Implementation and assessment of the performance of several of movement schemes in two dimensions 
          - 1. Biased Random Walks (BRW) 
          - 2. Correlated Random Walks (CRW) 
          - 3. Biased Correlated Random Walks (BCRW)
        image: https://fox8.com/wp-content/uploads/sites/12/2021/06/sheep.jpg?w=1280
        # featured:
        #   name: Demo
        #   link: https://hugo-profile.netlify.app
        badges:
          - "Python"
          - "Modelling"
          - "Biology"
        links:
          # - icon: fa fa-envelope
          #   url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/JacobKohav/Walk
          # - icon: fab fa-twitter
          #   url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Course-Grained Simulation of a Protein
        content: Protein structure prediction through a dynamics simulation through a two dimensional coarse-grained model of a protein which consists of a chain of N amino acids. Each amino acid is represented by a circle connected to amino acids via an harmonic spring potential.
        image: https://i.pinimg.com/originals/7e/42/57/7e4257461ea477895873e320dfce9ff5.png
        # featured:
        #   name: Demo
        #   link: https://django-converter.herokuapp.com
        badges:
          - "Python"
          - "Modelling"
          - "Biology"
        links:
          - icon: fab fa-github
            url: https://github.com/JacobKohav/Protein#course-grained-simulation-of-a-protein

      - title: Simulation of Flocks
        content: Illustration of swarm intelligence through a flocking example utilizing coherent emergent behavior (focking) of a swarm, when each agent is 1. Attracted to other agents 2. Repulsed when too close to other agents 3. Performing velocity alignment with other agents Examination of this behavior in 2D; the swarm will be composed of N agents; each agent will be defined by its position (p) and velocity (v).

        # image: /resources/_gen/images/Simulation_of_Flocks.jpg
        image: https://media.istockphoto.com/id/1050922264/vector/vector-cartoon-seagulls-flying-in-the-air.jpg?s=612x612&w=0&k=20&c=F_TqNVATVnmwVseTE987pmX0nXtBB8glCDJOFwq-MO4=
        # featured:
        #   name: Demo V2
        #   link: https://hugo-profile-2.netlify.app
        badges:
          - "Python"
          - "Modelling"
          - "Biology"
        links:
          - icon: fab fa-github
            url: https://github.com/JacobKohav/Flock

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: jacob.kohav@colorado.edu
    btnName: Mail me

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: false
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/JacobKohav
      linkedin: https://www.linkedin.com/in/jacob-kohav/
      # envelope: mailto:jacob.kohav@colorado.edu?subject=Connect%20with%20Jacob

      # twitter: https://twitter.com
      # instagram: https://instagram.com
      # facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false
